### ISSUE TITLE
HTTP: panic serving [client IP:Port goes here]: interface conversion: *osfs.OsFS is not avfs.VolumeManager: missing method VolumeAdd

### ISSUE THREAD

**Issue by Renkyz** [marcelGoerentz/Threadfin#35]
For a very long time I have been using the "Store buffer in RAM" option instead of having it write to the disk.
Today I decided to try have it write to the disk just to test things out and I'm recieving some sort of "panic" error and I have no idea what it means at all.

I'm running Threadfin 1.6 (0-beta) on Windows Server 2022

Here's what I see in the Threadfin window whenever I try to play a channel after unchecking store buffer in RAM:

```
2024/09/26 10:05:41 http: panic serving 192.168.0.100:56403: interface conversion: *osfs.OsFS is not avfs.VolumeManager: missing method VolumeAdd
goroutine 193 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:1903 +0xbe
panic({0xcaa880?, 0xc001cbd0e0?})
        /opt/hostedtoolcache/go/1.22.7/x64/src/runtime/panic.go:770 +0x132
threadfin/src.checkVFSFolder({0xc000c29560, 0x5d}, {0xe83488, 0xc001d0f380})
        /home/runner/work/Threadfin/Threadfin/src/toolchain.go:61 +0xb4
threadfin/src.bufferingStream({{0xc001d016cc, 0x4}, {0xc001d017c0, 0x9}, {0xc0024b54a0, 0x14}, {0xc0024b54b8, 0x17}, {0x0, 0x0}, ...}, ...)
        /home/runner/work/Threadfin/Threadfin/src/buffer.go:112 +0x476
threadfin/src.Stream({0xe7c830, 0xc001e2a540}, 0xc001fa9560)
        /home/runner/work/Threadfin/Threadfin/src/webserver.go:323 +0x1230
net/http.HandlerFunc.ServeHTTP(0xc002514820?, {0xe7c830?, 0xc001e2a540?}, 0xb120ba?)
        /opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:2171 +0x29
net/http.(*ServeMux).ServeHTTP(0x8892f9?, {0xe7c830, 0xc001e2a540}, 0xc001fa9560)
        /opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc001cbcd50?}, {0xe7c830?, 0xc001e2a540?}, 0x6?)
        /opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc000b18cf0, {0xe7d128, 0xc000518180})
        /opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 82
        /opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:3290 +0x4b4
```

**Comment by marcelGoerentz** [comment]
Hey,

should be fixed in latest beta. (https://github.com/marcelGoerentz/Threadfin/commit/8690e7c67069fc57816adb9a343ac30e47d96ded)

**Comment by Renkyz** [comment]
Awesome, thanks mate :) I'll try it out as soon as I have time.

**Comment by Renkyz** [comment]
Can confirm the bug is fixed and writing to disk is working great for myself and my friend. Thanks heaps mate!

**Comment by Renkyz** [comment]
So I forgot about this issue that if I remember right, has existed for a very long time.
When writing the buffer to the disk, these error messages flood the log over a short period of time. Never got these when writing to RAM. It seems to be a non-issue anyway as restarting the PC does indeed clear those temp files. But that repeated error text can be a bit annoying haha.

```
2024-10-22 19:45:35 [Threadfin] [ERROR] remove C:\Users\Administrator\AppData\Local\Temp\threadfin\2023-11-9MFQ-X9T1CJ\MGFA2YO23CIBAH9F6GIL\768e264c64f47a2e5e4410d3497ec934\4939.ts: The process cannot access the file because it is being used by another process. (Old temporary buffer file could not be deleted) - EC: 4007
2024-10-22 19:45:35 [Threadfin] [ERROR] remove C:\Users\Administrator\AppData\Local\Temp\threadfin\2023-11-9MFQ-X9T1CJ\MGFA2YO23CIBAH9F6GIL\768e264c64f47a2e5e4410d3497ec934\4940.ts: The process cannot access the file because it is being used by another process. (Old temporary buffer file could not be deleted) - EC: 4007
2024-10-22 19:45:49 [Threadfin] [ERROR] remove C:\Users\Administrator\AppData\Local\Temp\threadfin\2023-11-9MFQ-X9T1CJ\MGFA2YO23CIBAH9F6GIL\768e264c64f47a2e5e4410d3497ec934\4954.ts: The process cannot access the file because it is being used by another process. (Old temporary buffer file could not be deleted) - EC: 4007
2024-10-22 19:45:49 [Threadfin] [ERROR] remove C:\Users\Administrator\AppData\Local\Temp\threadfin\2023-11-9MFQ-X9T1CJ\MGFA2YO23CIBAH9F6GIL\768e264c64f47a2e5e4410d3497ec934\4955.ts: The process cannot access the file because it is being used by another process. (Old temporary buffer file could not be deleted) - EC: 4007
2024-10-22 19:46:10 [Threadfin] [ERROR] remove C:\Users\Administrator\AppData\Local\Temp\threadfin\2023-11-9MFQ-X9T1CJ\MGFA2YO23CIBAH9F6GIL\768e264c64f47a2e5e4410d3497ec934\4974.ts: The process cannot access the file because it is being used by another process. (Old temporary buffer file could not be deleted) - EC: 4007
2024-10-22 19:46:10 [Threadfin] [ERROR] remove C:\Users\Administrator\AppData\Local\Temp\threadfin\2023-11-9MFQ-X9T1CJ\MGFA2YO23CIBAH9F6GIL\768e264c64f47a2e5e4410d3497ec934\4975.ts: The process cannot access the file because it is being used by another process. (Old temporary buffer file could not be deleted) - EC: 4007
2024-10-22 19:46:17 [Threadfin] [ERROR] remove C:\Users\Administrator\AppData\Local\Temp\threadfin\2023-11-9MFQ-X9T1CJ\MGFA2YO23CIBAH9F6GIL\768e264c64f47a2e5e4410d3497ec934\4988.ts: The process cannot access the file because it is being used by another process. (Old temporary buffer file could not be deleted) - EC: 4007
```
